FROM       ubuntu:trusty
MAINTAINER Abe Voelker <abe@abevoelker.com>

RUN \
# Install build dependencies
  apt-get update &&\
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
  wget build-essential &&\
# Install ruby-install
{{ include_file('includes/ruby-install') }}
# Install Ruby
  ruby-install {{ ruby_version }} &&\
# Install bundler globally
  PATH=$PATH:/opt/rubies/{{ ruby_version_hyphenated }}/bin gem install bundler &&\
# Remove build dependencies, clean up APT and temp files
  apt-get clean &&\
  DEBIAN_FRONTEND=noninteractive apt-get remove --purge -y wget build-essential &&\
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Set $PATH so that non-login shells will see the Ruby binaries
ENV PATH $PATH:/opt/rubies/{{ ruby_version_hyphenated }}/bin

# Add Ruby binaries to login shells's $PATH
COPY ./ruby.sh /etc/profile.d/ruby.sh
